name: 🚀 Деплой всего Nuxt.js проекта

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Получить код
        uses: actions/checkout@v4

      - name: 📦 Установить Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: 📦 Установить зависимости
        run: npm install

      - name: 🗑 Очистить кэш
        run: rm -rf .nuxt dist .output || true

      - name: 🔨 Собрать проект
        run: npm run build

      - name: 🔍 Проверить содержимое
        run: ls -la

      - name: 📁 Передать проект на сервер
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/var/www/blockclient"
          tar_dereference: true

      - name: 🔁 Перезапустить PM2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/blockclient
            npm install --production
            pm2 restart all