name: 🔧 Деплой Nuxt приложения

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Получить код из репозитория
        uses: actions/checkout@v4

      - name: 📦 Установить зависимости
        run: npm install

      - name: 🗑 Очистить кэш
        run: rm -rf .nuxt dist .output

      - name: 🔨 Собрать проект
        run: npm run build

      - name: 📁 Передать файлы на сервер (SCP)
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/var/www/blockclient"

      - name: 🔁 Перезапуск PM2 на сервере
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/blockclient
            pm2 restart all